runtime: nodejs8
instance_class: F1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic